### ISSUE TITLE
Invalid encoding

### ISSUE THREAD

**Issue by temi4** [nuxt-community/feed-module#4]
I'm using Cyrillic
```
feed: [
    {
      path: '/news.xml',
      async create(feed) { 
        feed.options = {
          title: 'Популярные новости России и мира',
          link: 'http://site.ru/feed.xml',
          description: 'Новости России и мира на сайте site.ru',
        }
        feed.addContributor({
          name: 'Команда проекта site.ru',
          email: 'support@ site.ru',
          link: 'http://site.ru/'
        })
      },
      cacheTime: 1000 * 60 * 15, // 15 min
      type: 'rss2'
    }
  ],
```

When I look feed in SRWare Iron browser, they show this: 
http://take.ms/6nnGeK
How is this fixed?

**Comment by manniL** [comment]
Thanks for the report! I'm looking into it :relaxed:

**Comment by manniL** [comment]
I've written a test for non-latin content and used the Cyrillic symbols from your example. It passed without problems. Also, I've tried to look into the created XML file with Firefox and everything looked fine. The issue is likely a browser-related issue and has nothing to do with the module directly.

![image](https://user-images.githubusercontent.com/640208/41626964-98659888-741e-11e8-9f07-d0fcf2a493ad.png)

**Comment by bactoria** [comment]
If you use **chrome**, please install **`RSS Subscription Extension (chrome extention)`**.

After that, it seems not to break.
